
 const activities = [
{
  id:301,
  title: "Black Peak",
  image: "/images/blackpuch.jpg",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  difficulty: "easy",
  region: "Uttarakhand",
  rating: 4,
  slug: "black-peak",
  isPopular: true
},

{
  id: 302 ,
  title: "Kamet",
  image: "/images/kamet.jpg",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  difficulty: "easy",
  region: "Uttarakhand",
  rating: 4,
  slug: "kamet-peak",
  isPopular: true
},
{
  id: 303,
  title: "Arwa Tower",
  image: "/images/arwa-tower.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Uttarakhand",
  difficulty: "easy",
  rating: 4,
  slug:"arwa-tower-peak",
  isPopular: true
},
{
  id: 304,
  title:"Neelkanth Peak",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Uttarakhand",
  difficulty: "easy",
  rating: 4,
  slug: "neelkanth-peak"
},

  {id:306,
  title:"Changabang Peak",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "changabang-peak"
},
  
  {id:309,
  title:"Pangarchulla Peak",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "pagarchulla-peak"
},
  {id:310,
  title:"Swargarohini I, II",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "swaragarohini-peak"
},
  {id:311,
  title:"Bhagirathi I, II & III",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "bhagirathi-peak"
},
  {id:312,
  title:"Gangotri I, II & III",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "gangotri-peak"
},
  {id:313,
  title:" Jogin I, II & III",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "jogin-peak"
},
  {id:314,
  title:"Thalay Sagar",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "thalaysagar-peak"
},
  {id:315,
  title:"Shivling peak",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "shivling-peak"
},
  {id:316,
  title:"Bhirgupanth",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Peak-Climbing",
   region: "Uttarakhand",
  rating: 4,
  slug: "bhrigupanth-peak"
},
  {id:317,
  title:"Chaukhamba",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Uttarakhand",
  rating: 4,
  slug: "chaukhamba-peak"
},
  {id:318,
  title:"Kedarnath",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Uttarakhand",
  rating: 4,
  slug: "kedarnath-peak"
},
  {id:319,
  title:"Kedardome",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Uttarakhand",
  rating: 4,
  slug: "kedardome-peak"
},
  {id:320,
  title:"Satopanth",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Uttarakhand",
  rating: 4,
  slug: "satopanth-peak"
},
  {id:321,
  title:"Trishul I, II, III",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Uttarakhand",
  rating: 4,
  slug: "trishul-peak"
},


  {id:323,
  title:"Mount Ladakhi",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4,
  slug: "mount-ladakhi"
},

  {id:324,
  title:"Mount Shitidhar",
  image: "/images/mountshitidar.jpg",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4,
  slug: "mount-shitidhar",
  isPopular: true
},


  {id:325,
  title:"Friendship Peak",
  image: "/images/friendship-peak.jpg",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4,
  slug: "friendship-peak",
  isPopular: true
},
  {id:326,
  title:"Seven Sisters",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4,
  slug: "seven-sisters",
  isPopular: true
},
  {id:327,
  title:"Mount Deo Tibba",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4,
  slug: "mount-deo-tibba"
},
  {id:328,
  title:"Mt. Menthosa",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4,
  slug: "mount-menthosa"
},
  {id:329,
  title:"Mt. Hanuman Tibba",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4,
  slug: "mount-hanuman-tibba"
},
,
 
  {id:330,
  title:" Mount Papsura",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4,
  slug: "mount-papsura"
},
  {id:3321,
  title:"Indrasan Peak",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4.5,
  slug: "indrasan-peak"
},       


  {id:3322,
  title:"Mount Yunam",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4.5,
  slug: "mount-yunam"
},

  {id:3323,
  title:"Mount CB-13 & CB-14",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Himachal",
  rating: 4.5,
  slug: "mount-cb-13-cb-14"
},

  {id:331,
  title:" Frey Peak",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Sikkim",
  rating: 4,
  slug: "frey-peak"
},
  {id:332,
  title:"Mt. Tenchenkhang",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Sikkim",
  rating: 4,
  slug: "mount-tenchenkang"
},
  {id:333,
  title:"Mount Jopuno",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Sikkim",
  rating: 4,
  slug: "mount-jopuno"
},
  {id:334,
  title:"Lama Wangden",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Sikkim",
  rating: 4,
  slug: "lama-wangden"
},
  {id:335,
  title:" Brumkhangse",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Peak-Climbing",
  region: "Sikkim",
  rating: 4,
  slug: "brumkhangse"
},


{
  id:336,
  title: "Himachal Mountain Bike Tour-1",
  duration: "13 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region: "Himachal",
  rating: 4,
  slug: "manali-leh-mountain-bike-tours"
},
{
  id: 337,
  title: "Himachal Mountain Bike Tour-2",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region: "Himachal",
  isPopular:true,
  rating: 4,
  slug: "kumaon-mountain-bike-tours"
},
{
  id: 338,
  title: "Himachal Mountain Bike Tour-3",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region: "Himachal",
  rating: 4,
  slug: "garhwal-mountain-bike-tours"
},
{
  id: 339,
  title: "Himachal Mountain Bike Tour-4",
  duration: "12 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  region: "Himachal",
  activity:"Mountain-Biking",
  isPopular:true,
  rating: 4,
  slug: "ladakh-mountain-bike-tours"
},
{
  id: 340,
  title: "Ladakh Mountain Bike Tour-1",
  duration: "16 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
   activity:"Mountain-Biking",
   region:"Ladakh",
  rating: 4,
  slug: "himachal-mountain-bike-tours"
},

{
  id: 341,
  title: "Ladakh Mountain Bike Tour-2",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Ladakh",
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34444,
  title: "Ladakh Mountain Bike Tour-3",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Ladakh",
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34445,
  title: "Ladakh Mountain Bike Tour-4",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Ladakh",
  isPopular:true,
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34446,
  title: "Garhwal Mountain Bike Tour-1",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Garhwal",
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34447,
  title: "Garhwal Mountain Bike Tour-2",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Garhwal",
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34448,
  title: "Garhwal Mountain Bike Tour-3",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Garhwal",
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34449,
  title: "Garhwal Mountain Bike Tour-4",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Garhwal",
  rating: 4,
  isPopular:true,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34449,
  title: "Kumaon Mountain Bike Tour-1",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:["Kumaon","Uttarakhand"],
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34450,
  title: "Kumaon Mountain Bike Tour-2",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:["Kumaon","Uttarakhand"],
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34451,
  title: "Kumaon Mountain Bike Tour-3",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:["Kumaon","Uttarakhand"],
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34452,
  title: "Kumaon Mountain Bike Tour-4",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:["Kumaon","Uttarakhand"],
  rating: 4,
  isPopular:true,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34453,
  title: "Uttarakhand Mountain Bike Tour-1",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Uttarakhand",
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34454,
  title: "Uttarakhand Mountain Bike Tour-2",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Uttarakhand",
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 34455,
  title: "Uttarakhand Mountain Bike Tour-3",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout finest Peaks in India",
  activity:"Mountain-Biking",
  region:"Uttarakhand",
  rating: 4,
  slug: "sikkim-mountain-bike-tours"
},
{
  id: 342,
  title: "Himachal Bike Tour-1",
  duration: "11 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout Our Finest Biking Tours",
  activity:"Motor-Biking",
  region: "Himachal",
  rating: 4,
  mostpopular:true,
  slug: "delhi-shimla-spiti-manali-motor-bike-tour"
},
{
  id: 343,
  title: "Himachal Bike Tour-2",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout Our Finest Biking Tours",
  activity:"Motor-Biking",
  region: "Himachal",
  rating:4,
   mostpopular:true,
  slug: "garhwal-motor-bike-tours"
},
{
  id: 344,
  title:"Himachal Bike Tour-3",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout Our Finest Biking Tours",
  activity:"Motor-Biking",
  region: "Himachal",
  rating: 4,
   mostpopular:true,
  slug: "ladakh-motor-bike-tours"
},
{
  id: 345,
  title: "Himachal Bike Tour-4",
  duration: "10 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout Our Finest Biking Tours",
   activity:"Motor-Biking",
  region: "Himachal",
  rating: 4,
  slug: "himachal-motor-bike-tours"
},
{
  id: 346,
  title: "Himachal Bike Tour-5",
  duration: "11 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout Our Finest Biking Tours",
  activity:"Motor-Biking",
  region: "Himachal",
  rating: 4,
  slug: "kumaon-motor-bike-tours"
},
{
  id: 3499,
  title: "Uttarakhand Bike Tour-1",
  duration: "11 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout Our Finest Biking Tours",
  activity:"Motor-Biking",
  region: "Uttarakhand",
  rating: 4,
  slug: "kumaon-motor-bike-tours"
},
{
  id: 4000,
  title: "Uttarakhand Bike Tour-2",
  duration: "11 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout Our Finest Biking Tours",
  activity:"Motor-Biking",
  region: "Uttarakhand",
  rating: 4,
  slug: "kumaon-motor-bike-tours"
},
{
  id: 4001,
  title: "Uttarakhand Bike Tour-3",
  duration: "11 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Checkout Our Finest Biking Tours",
  activity:"Motor-Biking",
  region: "Uttarakhand",
  rating: 4,
  slug: "kumaon-motor-bike-tours"
},
  {
    id: 4002,
    title: "Uttarakhand Bike Tour-4",
    duration: "11 Days",
    image: "/images/kolahoi-trek.webp",
    description: "Checkout Our Finest Biking Tours",
    activity:"Motor-Biking",
    region: "Uttarakhand",
    rating: 4,
    slug: "kumaon-motor-bike-tours"
  },
  {
    id: 4003,
    title: "Sikkim Bike Tour-1",
    duration: "11 Days",
    image: "/images/kolahoi-trek.webp",
    description: "Checkout Our Finest Biking Tours",
    activity:"Motor-Biking",
    region: "Sikkim",
    rating: 4,
    slug: "kumaon-motor-bike-tours"
  },
  {
    id: 4004,
    title: "Sikkim Bike Tour-2",
    duration: "11 Days",
    image: "/images/kolahoi-trek.webp",
    description: "Checkout Our Finest Biking Tours",
    activity:"Motor-Biking",
    region: "Sikkim",
    rating: 4,
    slug: "kumaon-motor-bike-tours"
  },
  {
    id: 4005,
    title: "Sikkim Bike Tour-3",
    duration: "11 Days",
    image: "/images/kolahoi-trek.webp",
    description: "Checkout Our Finest Biking Tours",
    activity:"Motor-Biking",
    region: "Sikkim",
    rating: 4,
    slug: "kumaon-motor-bike-tours"
  },

  {
    id: 4006,
    title: "Sikkim Bike Tour-4",
    duration: "11 Days",
    image: "/images/kolahoi-trek.webp",
    description: "Checkout Our Finest Biking Tours",
    activity:"Motor-Biking",
    region: "Sikkim",
    rating: 4,
    slug: "kumaon-motor-bike-tours"
  },
  {
    id: 4007,
    title: "Garhwal Bike Tour-1",
    duration: "11 Days",
    image: "/images/kolahoi-trek.webp",
    description: "Checkout Our Finest Biking Tours",
    activity:"Motor-Biking",
    region: "Garhwal",
    rating: 4,
    slug: "kumaon-motor-bike-tours"
  },
  {
    id: 4008,
    title: "Garhwal Bike Tour-2",
    duration: "11 Days",
    image: "/images/kolahoi-trek.webp",
    description: "Checkout Our Finest Biking Tours",
    activity:"Motor-Biking",
    region: "Garhwal",
    rating: 4,
    slug: "kumaon-motor-bike-tours"
  },
  {
    id: 4009,
    title: "Garhwal Bike Tour-3",
    duration: "11 Days",
    image: "/images/kolahoi-trek.webp",
    description: "Checkout Our Finest Biking Tours",
    activity:"Motor-Biking",
    region: "Garhwal",
    rating: 4,
    slug: "kumaon-motor-bike-tours"
  },



{
  id: 347,
  title: "Angling in Kali River",
  duration: " 6 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Angling in Kali River",
   activity:"Angling-Tours",
  rating: 4,
  slug: "angling-in-india"
},
{
  id: 348,
  title: "Angling in Kashmir Tours",
  duration: " 6 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Angling in Kashmir",
   activity:"Angling-Tours",
  rating: 4,
  slug: "angling-in-india"
},
{
  id: 349,
  title: "Angling in Sangla Valley",
  duration: " 09 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Angling in Kashmir",
   activity:"Angling-Tours",
  rating: 4,
  slug: "angling-in-india"
},

{
  id: 350,
  title: "Angling in Ramganga River",
  duration: " 11 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Angling in Kashmir",
   activity:"Angling-Tours",
  rating: 4,
  slug: "angling-in-india"
},
{
  id: 351,
  title: "Angling in Tirthan Valley",
  duration: "04 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Angling in Kashmir",
   activity:"Angling-Tours",
  rating: 4,
  slug: "angling-in-india"
},
{
  id: 352,
  title: "Gadhwal Himalayan Jeep Safari Tours",
  duration: "13 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
  region: "Garhwal",
   activity:"Jeep-Safari",
  rating: 4,
  slug: "jeep-safari-tours/garhwal-himalayan-jeepsafari-tours"
},

{
  id: 353,
  title: "Himachal Jeep Safari Tours",
  duration: "21 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
  region: "Himachal",
  activity:"Jeep-Safari",
  rating: 4,
  slug: "himachal-jeepsafari-tours"
},

{ id: 354,
  title: "Ladakh Jeep Safari Tours",
  duration: "15 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
  region: "Ladakh",
  activity:"Jeep-Safari",
  rating: 4,
  slug: "Ladakh-jeepsafari-tours"
},
{  id: 355,
  title: "Kumaon Jeep Safari Tours",
  duration: "02Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
   activity:"Jeep-Safari",
   region: ["Kumaon","Uttarakhand"],
  rating: 4,
  slug: "kumaon-jeepsafari-tours"
},
{  id: 356,
  title: "Manali to Leh Ladakh Trek",
  duration: " 12 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
   activity:"Jeep-Safari",
    region: "Manali-Ladakh",
  rating: 4,
  slug: "manali-to-leh-pangong-jeep-safari"
},

{  id: 357,
  title: "Char Dham Jeep Safari",
  duration: " 14 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
   activity:"Jeep-Safari",
   region: "Garhwal",
  rating: 4,
  slug: "chardham-jeep-safari"
},
{  id: 358,
  title: "Pangong Lake Jeep Safari with Nubra Valley",
  duration: " 07 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
   activity:"Jeep-Safari",
  region: "Ladakh",
  rating: 4,
  slug: "pangong-lake-tour"
},
{ id:359,
  title: "Trans Himalayan Jeep Safari Tour",
  duration: " 18 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
  activity:"Jeep-Safari",
  region: "Ladakh",
  rating: 4,
  slug: "trans-himalayan-tour"
},

{ id:360,
  title: "Amritsar - Dharamshala - Spiti Valley - Leh - Srinagar Jeep Safari",
  duration: "20 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
  activity:"Jeep-Safari",
  region: "Himachal",
  rating:4,
  slug: "amritsar-spiti-leh-srinagar-safari"
},
{ id:361,
  title: "Ladakh - Srinagar Jeep Safari",
  duration: " 09 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
   activity:"Jeep-Safari",
    region: "Ladakh",
  rating: 4,
  slug: "ladakh-srinagar-jeep-safari"
},
{ id:362,
  title: "Ladakh with Lamayuru & Tsomoriri Lake Jeep Safari Tour",
  duration: "07 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
   activity:"Jeep-Safari",
  region: "Ladakh",
  rating: 4,
  slug: "lamayuru-tsomoriri-lake-tour"
},
{ id:363,
  title: "Manali - Leh Jeep Safari Tour",
  duration: "12 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
  activity:"Jeep-Safari",
  region: "Himachal",
  rating: 4,
  slug: "manali-leh-jeep-safari"
},
{ id:364,
  title: "Old Hindustan Tibet Jeep Safari",
  duration: "13 Days",
  image: "/images/kolahoi-trek.webp",
  description: "Best of Jeep Safari Tours",
   activity:"Jeep-Safari",
    region: "Tibet",
  rating:4,
  slug: "old-hindustan-tibet-safari-expedition"
},
{ id:365,
  title: "East India Cycling Tours",
  duration: "15 Days",
  image: "/images/cycling-tour-east.jpg",
  description: "Best of Jeep Safari Tours",
  activity:"Cycling-Tours",
  region: "Ladakh",
  difficulty: "moderate",
  rating:4,
  slug: "cycling-tours/east-india"
},
{ id:366,
  title: "West India Cycling Tours",
  duration: "13 Days",
  image: "/images/cycling-tour-west.jpg",
  description: "Best of Jeep Safari Tours",
  activity:"Cycling-Tours",
   region: "Goa",
    difficulty: "moderate",
  rating:4,
  slug: "cycling-tours/west-india"
},
{ id:367,
  title: "North India Cycling Tours",
  duration: "09 Days",
  image: "/images/cycling-tour-north.jpg",
  description: "Best of Jeep Safari Tours",
   activity:"Cycling-Tours",
  region: "Delhi-Jaipur",
    difficulty: "moderate",
  rating:4,
  slug: "cycling-tours/north-india"
},
{ id:368,
  title: "South India Cycling Tours",
  duration: "10 Days",
  image: "/images/cycling-tour-south.jpg",
  description: "Best of Jeep Safari Tours",
  activity:"Cycling-Tours",
  region: "Bangalore-Kovalam",
   difficulty: "moderate",
  rating:4,
  slug: "cycling-tours/south-india"
},
]
 

export default activities
