export const peaksDataGarhwal = [

  {title: "garhwal Peaks" ,label:"View Garhwal peaks"},
  { name: 'Panwali Dwar (6663)', longitude: "79 57'", latitude: "30 17'", remarks: 'Song(RH) - Khati - Dwalio - Phukia - Base Camp - C - I,C - II and summit' },
  { name: 'Nanda Devi East (7437)', longitude: "79 59'", latitude: "30 21'", remarks: 'Munsyari (RH) - Lilam - martoli(Vill) - nasanpatti - Bhadeligwar BC - C - I,C - II,C - II and summit attempt' },
  { name: 'Nanda Khat (6545)', longitude: "79 58'", latitude: "30 18'", remarks: 'Bharari(RH) - Loharkhet - Khati - Dwali(Vill) - Base Camp,C - I,C - II,C - III summit attempt' },
  { name: 'Mrigthuni (6855)', longitude: "79 49'", latitude: "30 17''", remarks: '--' },
  { name: 'Maiktoli (6803)', longitude: "79 52'", latitude: "30 16", remarks: '--' },
  { name: 'Trishul-I (7120)', longitude: "76 46'", latitude: "30 18'", remarks: 'Ghat(RH) - Sitel - Sutol - Lat Kopri - Chandniya Ghat - BC - C - I,C - II,C - III and summit attempt' },
  { name: 'Trishul-II (6690)', longitude: "79 46'", latitude: "30 17'", remarks: '--' },
  { name: 'Trishul-III (6008)', longitude: "79 48'", latitude: "30 17'", remarks: '--' },
  { name: 'Tharkot (6099)', longitude: "79 49'", latitude: "30 13'", remarks: 'Bharari (RH) - Khati via Dhakuri - Jatolia - Sunder Dunga - Sukhran Cave BC - C - I,C - II,C - II and sumit attempt' },
  { name: 'Nanda Ghunti (6390)', longitude: "79 43'", latitude: "30 20'", remarks: 'Debal(RH) - Hemkund(BC) - Roopkund - attempt nanda ghunit via the Ronti Saddle' },
  { name: 'Ronti (6063)', longitude: "79 43'", latitude: "30 22'", remarks: '--' },
  { name: 'Bhanoti (5645)', longitude: "79 50'", latitude: "30 12'", remarks: 'Bharai (RH) Loharkhet - Dhakuri - Khati(Vill) Base Camp - C - I,C - II and summit attempt' },
  { name: 'Baljuri (5922)', longitude: "79 57'", latitude: "30 15'", remarks: 'Bharari(RH) - Loharkhet - Dhakuiri - Khati(Vill)Base Camp - C - I,C - II,C - III and summit attempt' },
  { name: 'Nanda Kot (6861)', longitude: "80 04'", latitude: "30 16'", remarks: 'Son(RH) - Loharkhet - Dhakuri Pass - Khati(Vill) - Dwali - C - I,C_II and summit attempt' },
  { name: 'Lepsa Dhura (5913)', longitude: "80 04'", latitude: "30 14'", remarks: '--' },
  { name: 'Unnamed Peak', longitude: "77 16'", latitude: "32 32'", remarks: 'Domphu Gompa (RH) Khoksar Nai - Tempala Pass (BC) - CiI summit attempt' },
  { name: 'Bara Sukha', longitude: "78 36'", latitude: "31 04'", remarks: 'Uttarkashi - Dunga - Pura(RH) - Tangua - Rania - base Camp - C - I & C - II then summit attempt' },
  { name: 'Rudugaira (5819)', longitude: "78 52'", latitude: "30 56'", remarks: 'Gangotri (RH) Tapovan - BC - then summit' },
  { name: 'Swargtrohini - I (6252)', longitude: "78 30'", latitude: "31 06'", remarks: 'Dehradun - natwar & Sankiri(RH) - Taluka - Osala - BC - BC - I and summit attempt' },
  { name: 'Swargtrohini - II (6278)', longitude: "78 33'", latitude: "31 00'", remarks: '--' },
  { name: 'Banderpunchi (6320)', longitude: "78 33'", latitude: "31 00'", remarks: '--' },
  { name: 'Sriknath (6133)', longitude: "78 48'", latitude: "30 57'", remarks: 'Uttarkashi - Bhatwari - Sukki(RH) - Hasilalsong Tel Gad Nullah - BC - I,BC - II and summit attempt' },
  { name: 'Gangotri-I (6672)', longitude: "78 50'", latitude: "30 55'", remarks: 'Gangotri(RH) - Ruduagira Nallah - BC - C - I,C - II and summit attempt' },
  { name: 'Gangotri - II (6590)', longitude: "78 51'", latitude: "30 54'", remarks: '--' },
  { name: 'Gangotri - III (6577)', longitude: "78 52'", latitude: "30 48'", remarks: '--' },
  { name: 'Joanali (6632)', longitude: "78 51'", latitude: "30 52'", remarks: '--' },
  { name: 'Jogin-I (6465)', longitude: "78 55'", latitude: "30 52'", remarks: '--' },
  { name: 'Jogin-II (6342)', longitude: "78 55'", latitude: "30 53'", remarks: 'Gangotri (RH) - Ruduagira nallah - BC - C - I - C - II and summit attempt' },
  { name: 'Jogin-III (6166)', longitude: "78 56'", latitude: "30 52'", remarks: '--' },
  { name: 'Thalaysagar (6904)', longitude: "78 59'", latitude: "30 51'", remarks: '--' },
  { name: 'Manda (6568)', longitude: "79 00'", latitude: "29 55'", remarks: 'Gangotri - Chirbas - BC - I,BC - II and summit attempt' },
  { name: 'Meru North (6450)', longitude: "79 02'", latitude: "29 52'", remarks: 'Gangotri - Chirbas - Gaumukh - Tapovan - BC - I,BC - II and summit attempt' },
  { name: 'Meru East (6261)', longitude: "79 02'", latitude: "29 52'", remarks: '--' },
  { name: 'Kirti Stambh (6270)', longitude: "79 01'", latitude: "30 49'", remarks: 'Gangotri - Chirbas - Gaumukh - BC - I,BC - II and summit attempt' },
  { name: 'Bhatekhunta (6578)', longitude: "79 02'", latitude: "30 48'", remarks: '--' },
  { name: 'Kedarnath (6962)', longitude: "79 04'", latitude: "30 47'", remarks: '--' },
  { name: 'Kedardome (6830)', longitude: "79 04'", latitude: "30 48'", remarks: '--' },
  { name: 'Karcha Kund (6632)', longitude: "79 07'", latitude: "30 46'", remarks: '--' },
  { name: 'Shivling (6543)', longitude: "79 04'", latitude: "30 52'", remarks: 'Gangotri - Gaumukh - Nandaban - BC - I,BC - II and sumit attempt' },
  { name: 'Bhagirathi - I (6856)', longitude: "79 09'", latitude: "30 51'", remarks: '--' },
  { name: 'Bhagirathi-II (6512)', longitude: "79 09'", latitude: "30 51'", remarks: '--' },
  { name: 'Bhagirathi-III (6454)', longitude: "79 08'", latitude: "30 52'", remarks: '--' },
  { name: 'Vasuki Parbat (6792)', longitude: "79 10'", latitude: "30 52'", remarks: '--' },
  { name: 'Satopanth (7075)', longitude: "79 13'",latitude: "30 50'", remarks: '--' },
  { name: 'Sundarshan Parbat (6507)', longitude: "79 05'",latitude: "30 58'", remarks: 'Gangtori - Gaumukh - BC - I,BC - II and summit attempt' },
  { name: 'Changabang (6866)', longitude: "79 55'",latitude: "30 29'", remarks: 'Joshimath (RH) Lata Vill. Belta - Latakhark - Dibrugatta - Uppr Deodi - BC - C - I,C - II and summit attempt' },
  
  { name: 'Changabang (6866)', longitude: "79 55'",latitude: "30 29'", remarks: 'Joshimath (RH) Lata Vill. Belta - Latakhark - Dibrugatta - Uppr Deodi - BC - C - I,C - II and summit attempt' },

  { name: 'Nikantha(6597)', longitude: "79 55'",latitude: "30 43'", remarks: 'Joshimath - Badrinath - BC - I and summit attempt' },

  { name: 'Chaukhamba-I (7138 )', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },

  { name: 'Chaukhamba-II (7070 )', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },
  
  { name: 'Chaukhamba-III (6995)', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },

  { name: 'Chaukhamba-III (6995)', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },

  { name: '	Chaukhamba-IV (6854 )', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },
  { name: 'Changuch ( 6322 )', longitude: "80 02'",latitude: "30 17'", remarks: 'Bharari (RH) - Loharkhet - Khati - Dwali Vill - Base Camp - C - I,C - II and summit attempt' },


]


export const peakdataHimachal = [
  {title: "Himachal Peaks" ,label:"View Himachal peaks"},
  { name: 'Panwali Dwar (6663)', longitude: "79 57'", latitude: "30 17'", remarks: 'Song(RH) - Khati - Dwalio - Phukia - Base Camp - C - I,C - II and summit' },
  { name: 'Nanda Devi East (7437)', longitude: "79 59'", latitude: "30 21'", remarks: 'Munsyari (RH) - Lilam - martoli(Vill) - nasanpatti - Bhadeligwar BC - C - I,C - II,C - II and summit attempt' },
  { name: 'Nanda Khat (6545)', longitude: "79 58'", latitude: "30 18'", remarks: 'Bharari(RH) - Loharkhet - Khati - Dwali(Vill) - Base Camp,C - I,C - II,C - III summit attempt' },
  { name: 'Mrigthuni (6855)', longitude: "79 49'", latitude: "30 17''", remarks: '--' },
  { name: 'Maiktoli (6803)', longitude: "79 52'", latitude: "30 16", remarks: '--' },
  { name: 'Trishul-I (7120)', longitude: "76 46'", latitude: "30 18'", remarks: 'Ghat(RH) - Sitel - Sutol - Lat Kopri - Chandniya Ghat - BC - C - I,C - II,C - III and summit attempt' },
  { name: 'Trishul-II (6690)', longitude: "79 46'", latitude: "30 17'", remarks: '--' },
  { name: 'Trishul-III (6008)', longitude: "79 48'", latitude: "30 17'", remarks: '--' },
  { name: 'Tharkot (6099)', longitude: "79 49'", latitude: "30 13'", remarks: 'Bharari (RH) - Khati via Dhakuri - Jatolia - Sunder Dunga - Sukhran Cave BC - C - I,C - II,C - II and sumit attempt' },
  { name: 'Nanda Ghunti (6390)', longitude: "79 43'", latitude: "30 20'", remarks: 'Debal(RH) - Hemkund(BC) - Roopkund - attempt nanda ghunit via the Ronti Saddle' },
  { name: 'Ronti (6063)', longitude: "79 43'", latitude: "30 22'", remarks: '--' },
  { name: 'Bhanoti (5645)', longitude: "79 50'", latitude: "30 12'", remarks: 'Bharai (RH) Loharkhet - Dhakuri - Khati(Vill) Base Camp - C - I,C - II and summit attempt' },
  { name: 'Baljuri (5922)', longitude: "79 57'", latitude: "30 15'", remarks: 'Bharari(RH) - Loharkhet - Dhakuiri - Khati(Vill)Base Camp - C - I,C - II,C - III and summit attempt' },
  { name: 'Nanda Kot (6861)', longitude: "80 04'", latitude: "30 16'", remarks: 'Son(RH) - Loharkhet - Dhakuri Pass - Khati(Vill) - Dwali - C - I,C_II and summit attempt' },
  { name: 'Lepsa Dhura (5913)', longitude: "80 04'", latitude: "30 14'", remarks: '--' },
  { name: 'Unnamed Peak', longitude: "77 16'", latitude: "32 32'", remarks: 'Domphu Gompa (RH) Khoksar Nai - Tempala Pass (BC) - CiI summit attempt' },
  { name: 'Bara Sukha', longitude: "78 36'", latitude: "31 04'", remarks: 'Uttarkashi - Dunga - Pura(RH) - Tangua - Rania - base Camp - C - I & C - II then summit attempt' },
  { name: 'Rudugaira (5819)', longitude: "78 52'", latitude: "30 56'", remarks: 'Gangotri (RH) Tapovan - BC - then summit' },
  { name: 'Swargtrohini - I (6252)', longitude: "78 30'", latitude: "31 06'", remarks: 'Dehradun - natwar & Sankiri(RH) - Taluka - Osala - BC - BC - I and summit attempt' },
  { name: 'Swargtrohini - II (6278)', longitude: "78 33'", latitude: "31 00'", remarks: '--' },
  { name: 'Banderpunchi (6320)', longitude: "78 33'", latitude: "31 00'", remarks: '--' },
  { name: 'Sriknath (6133)', longitude: "78 48'", latitude: "30 57'", remarks: 'Uttarkashi - Bhatwari - Sukki(RH) - Hasilalsong Tel Gad Nullah - BC - I,BC - II and summit attempt' },
  { name: 'Gangotri-I (6672)', longitude: "78 50'", latitude: "30 55'", remarks: 'Gangotri(RH) - Ruduagira Nallah - BC - C - I,C - II and summit attempt' },
  { name: 'Gangotri - II (6590)', longitude: "78 51'", latitude: "30 54'", remarks: '--' },
  { name: 'Gangotri - III (6577)', longitude: "78 52'", latitude: "30 48'", remarks: '--' },
  { name: 'Joanali (6632)', longitude: "78 51'", latitude: "30 52'", remarks: '--' },
  { name: 'Jogin-I (6465)', longitude: "78 55'", latitude: "30 52'", remarks: '--' },
  { name: 'Jogin-II (6342)', longitude: "78 55'", latitude: "30 53'", remarks: 'Gangotri (RH) - Ruduagira nallah - BC - C - I - C - II and summit attempt' },
  { name: 'Jogin-III (6166)', longitude: "78 56'", latitude: "30 52'", remarks: '--' },
  { name: 'Thalaysagar (6904)', longitude: "78 59'", latitude: "30 51'", remarks: '--' },
  { name: 'Manda (6568)', longitude: "79 00'", latitude: "29 55'", remarks: 'Gangotri - Chirbas - BC - I,BC - II and summit attempt' },
  { name: 'Meru North (6450)', longitude: "79 02'", latitude: "29 52'", remarks: 'Gangotri - Chirbas - Gaumukh - Tapovan - BC - I,BC - II and summit attempt' },
  { name: 'Meru East (6261)', longitude: "79 02'", latitude: "29 52'", remarks: '--' },
  { name: 'Kirti Stambh (6270)', longitude: "79 01'", latitude: "30 49'", remarks: 'Gangotri - Chirbas - Gaumukh - BC - I,BC - II and summit attempt' },
  { name: 'Bhatekhunta (6578)', longitude: "79 02'", latitude: "30 48'", remarks: '--' },
  { name: 'Kedarnath (6962)', longitude: "79 04'", latitude: "30 47'", remarks: '--' },
  { name: 'Kedardome (6830)', longitude: "79 04'", latitude: "30 48'", remarks: '--' },
  { name: 'Karcha Kund (6632)', longitude: "79 07'", latitude: "30 46'", remarks: '--' },
  { name: 'Shivling (6543)', longitude: "79 04'", latitude: "30 52'", remarks: 'Gangotri - Gaumukh - Nandaban - BC - I,BC - II and sumit attempt' },
  { name: 'Bhagirathi - I (6856)', longitude: "79 09'", latitude: "30 51'", remarks: '--' },
  { name: 'Bhagirathi-II (6512)', longitude: "79 09'", latitude: "30 51'", remarks: '--' },
  { name: 'Bhagirathi-III (6454)', longitude: "79 08'", latitude: "30 52'", remarks: '--' },
  { name: 'Vasuki Parbat (6792)', longitude: "79 10'", latitude: "30 52'", remarks: '--' },
  { name: 'Satopanth (7075)', longitude: "79 13'",latitude: "30 50'", remarks: '--' },
  { name: 'Sundarshan Parbat (6507)', longitude: "79 05'",latitude: "30 58'", remarks: 'Gangtori - Gaumukh - BC - I,BC - II and summit attempt' },
  { name: 'Changabang (6866)', longitude: "79 55'",latitude: "30 29'", remarks: 'Joshimath (RH) Lata Vill. Belta - Latakhark - Dibrugatta - Uppr Deodi - BC - C - I,C - II and summit attempt' },
  
  { name: 'Changabang (6866)', longitude: "79 55'",latitude: "30 29'", remarks: 'Joshimath (RH) Lata Vill. Belta - Latakhark - Dibrugatta - Uppr Deodi - BC - C - I,C - II and summit attempt' },

  { name: 'Nikantha(6597)', longitude: "79 55'",latitude: "30 43'", remarks: 'Joshimath - Badrinath - BC - I and summit attempt' },

  { name: 'Chaukhamba-I (7138 )', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },

  { name: 'Chaukhamba-II (7070 )', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },
  
  { name: 'Chaukhamba-III (6995)', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },

  { name: 'Chaukhamba-III (6995)', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },

  { name: '	Chaukhamba-IV (6854 )', longitude: "79 15'",latitude: "30 43'", remarks: 'Joshimath - Mana Vill. - BC - IBC - II ,BC - III and summit attempt' },
  { name: 'Changuch ( 6322 )', longitude: "80 02'",latitude: "30 17'", remarks: 'Bharari (RH) - Loharkhet - Khati - Dwali Vill - Base Camp - C - I,C - II and summit attempt' },


]